services:
  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    x-develop:
      watch:
        - action: sync
          path: ./backend
          target: /home/backend
    ports:
      - "8000:8000"
    env_file: .env
    restart: on-failure
    volumes:
      - ./media:/home/media
    depends_on:
      - postgres
      - redis

  node:
    build:
      context: .
      dockerfile: node.dockerfile
    ports:
      - "5173:5173"
    user: node
    env_file: .env
    volumes:
      - ./src:/home/node/src
      - ./dist:/home/node/dist
#      - /home/node/node_modules
      - ./node_modules:/home/node/node_modules
    restart: on-failure
    x-develop:
      watch:
        - action: sync
          path: ./vite.config.js
          target: /home/node/vite.config.js
        - action: rebuild
          path: ./package.json
          target: /home/node/package.json
    depends_on:
      - backend

  postgres:
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine3.18
    ports:
    - "6379:6379"
